# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(name: "admin", password: "admin")
User.create(name: "horst", password: "horst")
User.create(name: "klaus", password: "klaus")
User.create(name: "guenther", password: "guenther")
User.create(name: "harald", password: "harald")

Employee.create(vorname: "Dennis", nachname: "Burat", personalnummer: "343")
Employee.create(vorname: "Karl", nachname: "Heinz", personalnummer: "15")
Employee.create(vorname: "Ernst", nachname: "August", personalnummer: "56")
Employee.create(vorname: "Harald", nachname: "Knopf", personalnummer: "62")
Employee.create(vorname: "Moritz", nachname: "Von der Ohe", personalnummer: "255")
Employee.create(vorname: "Klaus", nachname: "Meier", personalnummer: "2")
Employee.create(vorname: "Horst", nachname: "Lippe", personalnummer: "33")

Tool.create(hersteller: "Knipex", modell: "Seitenschneider klein", barcode: "3354965", lagerbestand: "153", mindestbestand: "10", anzahl_ersatz: "23")
Tool.create(hersteller: "Knipex", modell: "Seitenschneider groß", barcode: "3354966", lagerbestand: "10", mindestbestand: "10", anzahl_ersatz: "0")
Tool.create(hersteller: "Knipex", modell: "Spitzzange klein", barcode: "3354967", lagerbestand: "24", mindestbestand: "10", anzahl_ersatz: "10")
Tool.create(hersteller: "Knipex", modell: "Spitzzange groß", barcode: "3354968", lagerbestand: "5", mindestbestand: "10", anzahl_ersatz: "0")
Tool.create(hersteller: "Knipex", modell: "Schnabelzange klein", barcode: "3354969", lagerbestand: "17", mindestbestand: "5", anzahl_ersatz: "3")
Tool.create(hersteller: "Knipex", modell: "Schnabelzange groß", barcode: "3354970", lagerbestand: "3", mindestbestand: "5", anzahl_ersatz: "0")
Tool.create(hersteller: "Wera", modell: "Schraubendreher PH1", barcode: "3354971", lagerbestand: "5", mindestbestand: "20", anzahl_ersatz: "7")
Tool.create(hersteller: "Wera", modell: "Schraubendreher PH2", barcode: "3354972", lagerbestand: "7", mindestbestand: "20", anzahl_ersatz: "0")
Tool.create(hersteller: "Wera", modell: "Schraubendreher PZ1", barcode: "3354973", lagerbestand: "35", mindestbestand: "20", anzahl_ersatz: "9")
Tool.create(hersteller: "Wera", modell: "Schraubendreher PZ2", barcode: "3354974", lagerbestand: "66", mindestbestand: "20", anzahl_ersatz: "15")
Tool.create(hersteller: "Garant", modell: "Maulschlüssel 9 Zoll", barcode: "3354975", lagerbestand: "3", mindestbestand: "5", anzahl_ersatz: "8")
Tool.create(hersteller: "Garant", modell: "Maulschlüssel 10 Zoll", barcode: "3354976", lagerbestand: "7", mindestbestand: "5", anzahl_ersatz: "5")
Tool.create(hersteller: "Garant", modell: "Maulschlüssel 11 Zoll", barcode: "3354977", lagerbestand: "2", mindestbestand: "5", anzahl_ersatz: "0")
Tool.create(hersteller: "Garant", modell: "Maulschlüssel 12 Zoll", barcode: "3354978", lagerbestand: "0", mindestbestand: "5", anzahl_ersatz: "0")
Tool.create(hersteller: "Garant", modell: "Maulschlüssel 13 Zoll", barcode: "3354979", lagerbestand: "4", mindestbestand: "5", anzahl_ersatz: "2")

Machine.create(hersteller: "Bosch", modell: "Bohrhammer SDS", barcode: "6364283", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364284", ausgeliehen: "false")
Machine.create(hersteller: "Bosch", modell: "Stichsäge", barcode: "6364285", ausgeliehen: "false")
Machine.create(hersteller: "Bosch", modell: "Bohrhammer SDS", barcode: "6364286", ausgeliehen: "false")
Machine.create(hersteller: "Bosch", modell: "Bohrhammer SDS", barcode: "6364287", ausgeliehen: "false")
Machine.create(hersteller: "Bosch", modell: "Bohrhammer SDS", barcode: "6364288", ausgeliehen: "false")
Machine.create(hersteller: "Bosch", modell: "Bohrhammer SDS", barcode: "6364289", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364290", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364291", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364292", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364293", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364294", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364295", ausgeliehen: "false")
Machine.create(hersteller: "Dewalt", modell: "Akkuschrauber", barcode: "6364296", ausgeliehen: "false")

Employee.first.indexmachines.create(ausgeliehen: true, ausgegeben_am: "2016-05-05", machine_id: 2, ausgegeben_von: "admin")
Employee.first.indexmachines.create(ausgeliehen: false, ausgegeben_am: "2016-05-05", machine_id: 3, ausgegeben_von: "admin")
Employee.first.indexmachines.create(ausgeliehen: true, ausgegeben_am: "2016-10-22", machine_id: 4, ausgegeben_von: "admin")
Employee.second.indexmachines.create(ausgeliehen: false, ausgegeben_am: "2016-05-05", machine_id: 5, ausgegeben_von: "admin")